<?php
declare(strict_types=1);

return [
    'draper' => [
        'label' => 'Draper',
        'location_phrase' => 'in Draper, Utah',
        'intro' => 'Elite Smiles is located in Draper, giving local patients convenient access to a private, doctor-led {procedure_label_lower} consultation close to home or work.',
        'route' => 'Our office is on South State Street near I-15 access, serving Draper and surrounding South Valley communities.',
        'travel_time' => 'Usually 5–15 minutes within Draper',
        'distance' => 'Varies by neighborhood',
        'nearby' => ['South Jordan', 'Sandy', 'Riverton', 'Herriman'],
    ],
    'lehi' => [
        'label' => 'Lehi',
        'location_phrase' => 'near Lehi, Utah',
        'intro' => 'Patients from Lehi often compare providers across Utah County and the South Valley when planning {procedure_label_lower}. Elite Smiles offers a focused consultation in Draper for patients who value careful planning and a natural-looking result.',
        'route' => 'The most direct trip typically follows I-15 north from Lehi to the Draper area.',
        'travel_time' => 'Typically about 20–30 minutes',
        'distance' => 'Approximately 17 miles',
        'nearby' => ['Traverse Mountain', 'Point of the Mountain', 'Highland', 'American Fork'],
    ],
    'south-jordan' => [
        'label' => 'South Jordan',
        'location_phrase' => 'near South Jordan, Utah',
        'intro' => 'For South Jordan patients exploring {procedure_label_lower}, Elite Smiles provides a nearby Draper option centered on individualized recommendations rather than a one-size-fits-all treatment plan.',
        'route' => 'Patients commonly reach the office using Bangerter Highway, 12300 South, or I-15 depending on their starting neighborhood.',
        'travel_time' => 'Typically about 15–25 minutes',
        'distance' => 'Approximately 10–15 miles',
        'nearby' => ['Daybreak', 'Riverton', 'Draper', 'Sandy'],
    ],
    'highland' => [
        'label' => 'Highland',
        'location_phrase' => 'for Highland, Utah Patients',
        'intro' => 'Highland patients considering {procedure_label_lower} may be willing to travel beyond the closest office when treatment quality, thoughtful planning, and a believable result are the priorities.',
        'route' => 'The drive generally follows Timpanogos Highway or local routes toward I-15 and Draper.',
        'travel_time' => 'Typically about 25–35 minutes',
        'distance' => 'Approximately 22 miles',
        'nearby' => ['Alpine', 'Cedar Hills', 'Lehi', 'American Fork'],
    ],
    'alpine' => [
        'label' => 'Alpine',
        'location_phrase' => 'for Alpine, Utah Patients',
        'intro' => 'Patients traveling from Alpine for {procedure_label_lower} often prioritize clinical judgment, privacy, and treatment designed to complement the individual rather than follow a standard cosmetic formula.',
        'route' => 'Most trips connect through Highland or Timpanogos Highway before continuing toward I-15 and Draper.',
        'travel_time' => 'Typically about 30–40 minutes',
        'distance' => 'Approximately 25 miles',
        'nearby' => ['Highland', 'Cedar Hills', 'Lehi', 'American Fork'],
    ],
    'cedar-hills' => [
        'label' => 'Cedar Hills',
        'location_phrase' => 'for Cedar Hills, Utah Patients',
        'intro' => 'Cedar Hills patients researching {procedure_label_lower} can use a Draper consultation to compare options, understand candidacy, and decide whether the recommended approach fits their goals.',
        'route' => 'The trip commonly follows local roads toward Timpanogos Highway and I-15 before reaching South State Street in Draper.',
        'travel_time' => 'Typically about 30–40 minutes',
        'distance' => 'Approximately 25 miles',
        'nearby' => ['Highland', 'Alpine', 'American Fork', 'Lehi'],
    ],
    'park-city' => [
        'label' => 'Park City',
        'location_phrase' => 'for Park City, Utah Patients',
        'intro' => 'For Park City patients, selecting the right provider for {procedure_label_lower} may matter more than selecting the nearest office. Elite Smiles offers a private Draper consultation focused on clarity, design judgment, and realistic expectations.',
        'route' => 'The usual route travels west on I-80 and south through the Salt Lake Valley toward Draper; weather can materially affect travel time.',
        'travel_time' => 'Typically about 45–60 minutes',
        'distance' => 'Approximately 40 miles',
        'nearby' => ['Kimball Junction', 'Summit Park', 'Salt Lake City', 'Draper'],
    ],
    'farmington' => [
        'label' => 'Farmington',
        'location_phrase' => 'for Farmington, Utah Patients',
        'intro' => 'Farmington patients planning {procedure_label_lower} may choose a Draper consultation when they want additional perspective, a detailed treatment discussion, and time to compare options carefully.',
        'route' => 'The drive generally follows I-15 south through Davis County and the Salt Lake Valley to Draper.',
        'travel_time' => 'Typically about 45–60 minutes',
        'distance' => 'Approximately 45 miles',
        'nearby' => ['Kaysville', 'Centerville', 'Bountiful', 'Salt Lake City'],
    ],
];
