<?php
declare(strict_types=1);

/**
 * Elite Smiles patient intake and consent packet.
 *
 * Version 4 digitizes the practice's current paper forms, gives each legal
 * consent its own patient initials and signature, and protects collected Social
 * Security numbers with encrypted storage and masked review output.
 */

if (!function_exists('patient_experience_packet_definition')) {
    function patient_experience_packet_definition(): array
    {
        return [
            'packet_key' => 'elite_smiles_patient_intake',
            'version' => 4,
            'title' => 'Elite Smiles Patient Forms',
            'description' => 'Patient information, health history, practice policies, and individual digital consents.',
            'sections' => [
                [
                    'section_key' => 'welcome',
                    'template_key' => 'elite_smiles_welcome',
                    'title' => 'Welcome to Elite Smiles',
                    'description' => 'A quick introduction before the patient forms begin.',
                    'category' => 'intake',
                    'fields' => [
                        [
                            'key' => 'welcome_title',
                            'type' => 'heading',
                            'label' => 'Welcome',
                        ],
                        [
                            'key' => 'welcome_message',
                            'type' => 'paragraph',
                            'label' => 'We are pleased to welcome you to our practice. Please complete these forms as fully as you can. If you have questions, our team will be glad to help. We look forward to working with you to maintain your dental health.',
                        ],
                        [
                            'key' => 'welcome_privacy',
                            'type' => 'paragraph',
                            'label' => 'Your answers and signatures are saved securely to your patient intake record.',
                        ],
                    ],
                ],
                [
                    'section_key' => 'patient_information',
                    'template_key' => 'elite_smiles_patient_information',
                    'title' => 'Patient Information',
                    'description' => 'Contact and personal information.',
                    'category' => 'intake',
                    'fields' => [
                        ['key' => 'patient_first_name', 'type' => 'text', 'label' => 'First name', 'required' => true],
                        ['key' => 'patient_middle_initial', 'type' => 'text', 'label' => 'Middle initial'],
                        ['key' => 'patient_last_name', 'type' => 'text', 'label' => 'Last name', 'required' => true],
                        ['key' => 'patient_dob', 'type' => 'dob', 'label' => 'Date of birth', 'required' => true],
                        ['key' => 'patient_age', 'type' => 'text', 'label' => 'Age'],
                        ['key' => 'patient_ssn', 'type' => 'ssn', 'label' => 'Social Security number', 'sensitive' => true],
                        ['key' => 'patient_phone', 'type' => 'phone', 'label' => 'Phone', 'required' => true],
                        ['key' => 'patient_alt_phone', 'type' => 'phone', 'label' => 'Alternate phone'],
                        ['key' => 'patient_email', 'type' => 'email', 'label' => 'Email', 'required' => true],
                        ['key' => 'patient_address', 'type' => 'text', 'label' => 'Street address', 'required' => true],
                        ['key' => 'patient_city', 'type' => 'text', 'label' => 'City', 'required' => true],
                        ['key' => 'patient_state', 'type' => 'text', 'label' => 'State', 'required' => true],
                        ['key' => 'patient_zip', 'type' => 'text', 'label' => 'ZIP code', 'required' => true],
                        [
                            'key' => 'patient_sex',
                            'type' => 'radio',
                            'label' => 'Sex',
                            'options' => ['Female', 'Male', 'Other', 'Prefer not to answer'],
                        ],
                        [
                            'key' => 'patient_marital_status',
                            'type' => 'dropdown',
                            'label' => 'Marital status',
                            'options' => ['Single', 'Married', 'Partnered', 'Separated', 'Divorced', 'Widowed', 'Minor'],
                        ],
                        ['key' => 'patient_partnered_years', 'type' => 'text', 'label' => 'Partnered for how many years?', 'visible_if' => ['field' => 'patient_marital_status', 'value' => 'Partnered']],
                        ['key' => 'patient_employer_school', 'type' => 'text', 'label' => 'Employer or school'],
                        ['key' => 'patient_occupation', 'type' => 'text', 'label' => 'Occupation'],
                        ['key' => 'patient_employer_address', 'type' => 'text', 'label' => 'Employer or school address'],
                        ['key' => 'patient_employer_phone', 'type' => 'phone', 'label' => 'Employer or school phone'],
                        ['key' => 'referral_source', 'type' => 'text', 'label' => 'Whom may we thank for referring you?'],
                        ['key' => 'emergency_contact', 'type' => 'emergency_contact', 'label' => 'Emergency contact', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'insurance_information',
                    'template_key' => 'elite_smiles_insurance_information',
                    'title' => 'Insurance Information',
                    'description' => 'Primary and additional dental insurance.',
                    'category' => 'intake',
                    'fields' => [
                        ['key' => 'primary_insurance_heading', 'type' => 'heading', 'label' => 'Primary insurance'],
                        ['key' => 'primary_insurance', 'type' => 'insurance', 'label' => 'Primary insurance'],
                        ['key' => 'primary_responsible_person', 'type' => 'text', 'label' => 'Person responsible for account'],
                        ['key' => 'primary_relationship', 'type' => 'text', 'label' => 'Relationship to patient'],
                        ['key' => 'primary_responsible_phone', 'type' => 'phone', 'label' => 'Responsible person phone'],
                        ['key' => 'primary_responsible_address', 'type' => 'text', 'label' => 'Responsible person address, if different'],
                        ['key' => 'primary_responsible_employer', 'type' => 'text', 'label' => 'Responsible person employer'],
                        ['key' => 'primary_responsible_occupation', 'type' => 'text', 'label' => 'Responsible person occupation'],
                        ['key' => 'primary_responsible_business_address', 'type' => 'text', 'label' => 'Responsible person business address'],
                        ['key' => 'primary_responsible_business_phone', 'type' => 'phone', 'label' => 'Responsible person business phone'],
                        ['key' => 'primary_contract_number', 'type' => 'text', 'label' => 'Contract number'],
                        ['key' => 'primary_dependents', 'type' => 'textarea', 'label' => 'Other dependents covered by this plan'],
                        ['key' => 'insurance_divider', 'type' => 'divider', 'label' => 'Additional insurance'],
                        ['key' => 'has_additional_insurance', 'type' => 'yes_no', 'label' => 'Is the patient covered by additional insurance?', 'required' => true],
                        ['key' => 'additional_insurance', 'type' => 'insurance', 'label' => 'Additional insurance'],
                        ['key' => 'additional_relationship', 'type' => 'text', 'label' => 'Additional subscriber relationship to patient'],
                        ['key' => 'additional_subscriber_phone', 'type' => 'phone', 'label' => 'Additional subscriber phone'],
                        ['key' => 'additional_subscriber_address', 'type' => 'text', 'label' => 'Additional subscriber address, if different'],
                        ['key' => 'additional_subscriber_employer', 'type' => 'text', 'label' => 'Additional subscriber employer'],
                        ['key' => 'additional_subscriber_business_phone', 'type' => 'phone', 'label' => 'Additional subscriber business phone'],
                        ['key' => 'additional_contract_number', 'type' => 'text', 'label' => 'Additional contract number'],
                        ['key' => 'additional_dependents', 'type' => 'textarea', 'label' => 'Other dependents covered by the additional plan'],
                    ],
                ],
                [
                    'section_key' => 'dental_history',
                    'template_key' => 'elite_smiles_dental_history',
                    'title' => 'Dental History',
                    'description' => 'Current concerns and previous dental care.',
                    'category' => 'health_history',
                    'fields' => [
                        ['key' => 'visit_reason', 'type' => 'textarea', 'label' => "Reason for today's visit", 'required' => true],
                        ['key' => 'former_dentist', 'type' => 'text', 'label' => 'Former dentist'],
                        ['key' => 'former_dentist_address', 'type' => 'text', 'label' => 'Former dentist address'],
                        ['key' => 'last_dental_care', 'type' => 'date', 'label' => 'Date of last dental care'],
                        ['key' => 'last_dental_xrays', 'type' => 'date', 'label' => 'Date of last dental X-rays'],
                        [
                            'key' => 'dental_concerns',
                            'type' => 'checkbox_group',
                            'label' => 'Please select any problems you have experienced',
                            'options' => [
                                'Bad breath',
                                'Bleeding gums',
                                'Clicking or popping jaw',
                                'Food collection between teeth',
                                'Grinding teeth',
                                'Loose teeth or broken fillings',
                                'Periodontal treatment',
                                'Sensitivity to cold',
                                'Sensitivity to hot',
                                'Sensitivity to sweets',
                                'Sensitivity when biting',
                                'Sores or growths in the mouth',
                                'None of the above',
                            ],
                        ],
                        ['key' => 'floss_frequency', 'type' => 'text', 'label' => 'How often do you floss?'],
                        ['key' => 'brush_frequency', 'type' => 'text', 'label' => 'How often do you brush?'],
                    ],
                ],
                [
                    'section_key' => 'medical_history',
                    'template_key' => 'elite_smiles_medical_history',
                    'title' => 'Medical History',
                    'description' => 'Health information relevant to safe dental care.',
                    'category' => 'health_history',
                    'fields' => [
                        ['key' => 'physician_name', 'type' => 'text', 'label' => "Physician's name"],
                        ['key' => 'physician_last_visit', 'type' => 'date', 'label' => 'Date of last physician visit'],
                        ['key' => 'bisphosphonate_history', 'type' => 'yes_no', 'label' => 'Have you ever used a bisphosphonate medication such as Fosamax, Actonel, Atelvia, Didronel, or Boniva?', 'required' => true],
                        ['key' => 'fen_phen_history', 'type' => 'yes_no', 'label' => 'Have you ever taken drugs collectively referred to as fen-phen, including combinations containing phentermine, fenfluramine, or dexfenfluramine?', 'required' => true],
                        ['key' => 'serious_illness_operations', 'type' => 'yes_no', 'label' => 'Have you had any serious illnesses or operations?', 'required' => true],
                        ['key' => 'serious_illness_details', 'type' => 'textarea', 'label' => 'If yes, please describe'],
                        ['key' => 'blood_transfusion', 'type' => 'yes_no', 'label' => 'Have you ever had a blood transfusion?', 'required' => true],
                        ['key' => 'blood_transfusion_dates', 'type' => 'text', 'label' => 'If yes, approximate dates'],
                        ['key' => 'pregnancy_status', 'type' => 'yes_no', 'label' => 'Are you pregnant?'],
                        ['key' => 'nursing_status', 'type' => 'yes_no', 'label' => 'Are you nursing?'],
                        ['key' => 'birth_control', 'type' => 'yes_no', 'label' => 'Are you taking birth control medication?'],
                        [
                            'key' => 'medical_conditions',
                            'type' => 'checkbox_group',
                            'label' => 'Please select any conditions you have or have had',
                            'options' => [
                                'Anemia', 'Arthritis or rheumatism', 'Artificial heart valves', 'Artificial joints', 'Asthma',
                                'Back problems', 'Blood disease', 'Cancer', 'Chemical dependency', 'Chemotherapy',
                                'Circulatory problems', 'Cortisone treatments', 'Persistent cough', 'Coughing up blood',
                                'Diabetes', 'Epilepsy', 'Fainting', 'Glaucoma', 'Headaches', 'Heart murmur',
                                'Heart problems', 'Hemophilia', 'Hepatitis', 'High blood pressure', 'HIV/AIDS',
                                'Jaw pain', 'Kidney disease', 'Liver disease', 'Mitral valve prolapse', 'Pacemaker',
                                'Radiation treatment', 'Respiratory disease', 'Rheumatic fever', 'Scarlet fever',
                                'Shortness of breath', 'Skin rash', 'Stroke', 'Swelling of feet or ankles',
                                'Thyroid problems', 'Tobacco habit', 'Tonsillitis', 'Tuberculosis', 'Ulcer',
                                'Sexually transmitted disease', 'None of the above',
                            ],
                        ],
                        ['key' => 'current_medications', 'type' => 'textarea', 'label' => 'List medications you are currently taking'],
                        ['key' => 'allergies', 'type' => 'textarea', 'label' => 'List medication, latex, or other allergies'],
                    ],
                ],
                [
                    'section_key' => 'information_authorization',
                    'template_key' => 'elite_smiles_information_authorization',
                    'title' => 'Insurance and Information Authorization',
                    'description' => 'Authorization for insurance benefits, payment, and health information use.',
                    'category' => 'consent',
                    'fields' => [
                        ['key' => 'authorization_heading', 'type' => 'heading', 'label' => 'Authorization'],
                        [
                            'key' => 'authorization_text',
                            'type' => 'paragraph',
                            'label' => 'I certify that I and/or my dependents have the insurance coverage identified in this intake and assign directly to the treating dentist all insurance benefits, if any, otherwise payable to me for services rendered. I understand that I am financially responsible for all charges whether or not paid by insurance, and I authorize the use of my signature on insurance submissions.',
                        ],
                        [
                            'key' => 'authorization_disclosure_text',
                            'type' => 'paragraph',
                            'label' => 'The treating dentist may use my health care information and disclose it to the insurance companies identified in this intake and their agents for obtaining payment, determining insurance benefits, or determining benefits payable for related services. This consent ends when my current treatment plan is completed or one year from the date signed, whichever occurs first.',
                        ],
                        ['key' => 'authorization_payment_text', 'type' => 'paragraph', 'label' => 'Payment is due in full at the time of treatment unless prior arrangements have been approved.'],
                        ['key' => 'authorization_signer_name', 'type' => 'text', 'label' => 'Printed name of patient, parent, guardian, or personal representative', 'required' => true],
                        ['key' => 'authorization_relationship', 'type' => 'text', 'label' => 'Relationship to patient', 'required' => true],
                        ['key' => 'authorization_initials', 'type' => 'digital_initials', 'label' => 'Initials: I have reviewed this authorization', 'required' => true],
                        ['key' => 'authorization_acknowledgement', 'type' => 'acknowledgement_checkbox', 'label' => 'I have read, understand, and authorize the terms above.', 'required' => true],
                        ['key' => 'authorization_signature', 'type' => 'digital_signature', 'label' => 'Signature of patient, parent, guardian, or personal representative', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'consent_to_proceed',
                    'template_key' => 'elite_smiles_consent_to_proceed',
                    'title' => 'Consent to Proceed',
                    'description' => 'General consent for preventive, restorative, therapeutic, and surgical dental care.',
                    'category' => 'consent',
                    'fields' => [
                        ['key' => 'proceed_heading', 'type' => 'heading', 'label' => 'Consent to Proceed'],
                        [
                            'key' => 'proceed_authorization',
                            'type' => 'paragraph',
                            'label' => 'I authorize Dr. Walter Meden and/or associates or assistants he may designate to perform procedures deemed necessary or advisable to maintain my dental health, or the dental health of any minor or other individual for whom I have responsibility. This includes the arrangement and/or administration of sedative agents, including nitrous oxide, analgesic, therapeutic, and other pharmaceutical agents related to restorative, therapeutic, or surgical treatments.',
                        ],
                        [
                            'key' => 'proceed_anesthetic_risks',
                            'type' => 'paragraph',
                            'label' => 'I understand that local anesthetic may cause an unexpected reaction or side effects, including bruising, hematoma, cardiac stimulation, muscle soreness, and temporary or, rarely, permanent numbness. Occasionally a needle may break and require surgical retrieval. Drops of local anesthetic may contact the eyes or facial tissues and cause temporary irritation.',
                        ],
                        [
                            'key' => 'proceed_treatment_risks',
                            'type' => 'paragraph',
                            'label' => 'I understand that during and after preventive procedures and basic dentistry, including cleanings and fillings, teeth may remain sensitive or painful. Dental materials and medications may trigger allergic or sensitivity reactions. After a lengthy appointment, jaw muscles may be sore or tender. Holding the mouth open can precipitate a temporomandibular joint disorder in a predisposed patient. Gums and surrounding tissues may be sensitive or painful, and the tongue, cheek, or other oral tissues may rarely be abraded or lacerated, sometimes requiring sutures or additional treatment.',
                        ],
                        [
                            'key' => 'proceed_foreign_object_risks',
                            'type' => 'paragraph',
                            'label' => 'I understand that crowns, small dental instruments, drill components, or other items may be aspirated or swallowed during dental treatment. This unusual event may require X-rays by a physician or hospital and, rarely, bronchoscopy or another procedure for safe removal.',
                        ],
                        [
                            'key' => 'proceed_medication_disclosure',
                            'type' => 'paragraph',
                            'label' => 'I understand the need to disclose all prescription drugs currently or previously taken, including fen-phen drugs. I understand that drugs prescribed to prevent osteoporosis, including Fosamax, Boniva, or Actonel, may cause complications involving non-healing jaw bone after oral surgery or tooth extraction.',
                        ],
                        [
                            'key' => 'proceed_assumption',
                            'type' => 'paragraph',
                            'label' => 'I voluntarily assume the possible risks associated with general preventive and operative treatment in hopes of obtaining the desired result, which may or may not be achieved, for my benefit or the benefit of my minor child or ward. I acknowledge that the nature and purpose of the procedures have been explained to me as needed and that I have had the opportunity to ask questions.',
                        ],
                        ['key' => 'proceed_patient_name', 'type' => 'text', 'label' => 'Patient name', 'required' => true],
                        ['key' => 'proceed_signer_relationship', 'type' => 'text', 'label' => 'Signer relationship to patient', 'required' => true],
                        ['key' => 'proceed_initials', 'type' => 'digital_initials', 'label' => 'Initials: I have reviewed this consent', 'required' => true],
                        ['key' => 'proceed_acknowledgement', 'type' => 'acknowledgement_checkbox', 'label' => 'I have read and consent to the treatment terms above.', 'required' => true],
                        ['key' => 'proceed_signature', 'type' => 'digital_signature', 'label' => 'Signature of patient or legal guardian', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'hipaa_acknowledgement',
                    'template_key' => 'elite_smiles_hipaa_acknowledgement',
                    'title' => 'Privacy Practices Acknowledgment',
                    'description' => 'HIPAA notice acknowledgment and release preferences.',
                    'category' => 'consent',
                    'fields' => [
                        ['key' => 'hipaa_heading', 'type' => 'heading', 'label' => 'Notice of Privacy Practices Acknowledgment'],
                        [
                            'key' => 'hipaa_rights',
                            'type' => 'paragraph',
                            'label' => 'I understand that under the Health Insurance Portability and Accountability Act of 1996 (HIPAA), I have certain privacy rights regarding my protected health information. I understand that this information may be used to conduct, plan, and direct my treatment and follow-up among health care providers involved in my care; obtain payment from third-party payers; and conduct normal health care operations such as quality assessments and provider certifications.',
                        ],
                        [
                            'key' => 'hipaa_notice',
                            'type' => 'paragraph',
                            'label' => 'I acknowledge receiving access to the Elite Smiles Notice of Privacy Practices, which more completely describes uses and disclosures of my health information. I understand that the practice may change its privacy practices and that I may request a current copy of the notice at any time.',
                        ],
                        [
                            'key' => 'hipaa_restrictions',
                            'type' => 'paragraph',
                            'label' => 'I understand that I may request in writing that the practice restrict how my protected information is used or disclosed for treatment, payment, or health care operations. The practice is not required to agree to a requested restriction, but if it agrees, it will abide by that restriction as required.',
                        ],
                        ['key' => 'release_heading', 'type' => 'heading', 'label' => 'Additional Release of Information'],
                        [
                            'key' => 'release_preference',
                            'type' => 'radio',
                            'label' => 'Choose one',
                            'options' => ['I authorize release to the person named below', 'Do not release my information to anyone not otherwise authorized by law'],
                            'required' => true,
                        ],
                        ['key' => 'release_authorized_person', 'type' => 'text', 'label' => 'Authorized person name, if applicable'],
                        ['key' => 'release_relationship', 'type' => 'text', 'label' => 'Authorized person relationship to patient'],
                        ['key' => 'release_duration', 'type' => 'paragraph', 'label' => 'Any additional release authorization remains effective until I terminate it in writing.'],
                        ['key' => 'hipaa_patient_name', 'type' => 'text', 'label' => 'Patient name', 'required' => true],
                        ['key' => 'hipaa_signer_relationship', 'type' => 'text', 'label' => 'Signer relationship to patient', 'required' => true],
                        ['key' => 'hipaa_initials', 'type' => 'digital_initials', 'label' => 'Initials: I acknowledge these privacy practices', 'required' => true],
                        ['key' => 'hipaa_acknowledgement_checkbox', 'type' => 'acknowledgement_checkbox', 'label' => 'I acknowledge the privacy practices and release preference above.', 'required' => true],
                        ['key' => 'hipaa_signature', 'type' => 'digital_signature', 'label' => 'Patient or legal representative signature', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'office_insurance_policy',
                    'template_key' => 'elite_smiles_office_insurance_policy',
                    'title' => 'Office and Insurance Policy',
                    'description' => 'Insurance, financial, treatment, and appointment responsibilities.',
                    'category' => 'consent',
                    'fields' => [
                        ['key' => 'insurance_policy_heading', 'type' => 'heading', 'label' => 'Insurance Benefits'],
                        [
                            'key' => 'insurance_policy_text',
                            'type' => 'paragraph',
                            'label' => 'Elite Smiles recognizes the importance of dental insurance. I understand that I am responsible for reviewing my policy or contacting my carrier about benefits, frequencies, limitations, restrictions, deductibles, and annual maximums. Dental insurance is a contract between me and my insurance company. The practice assists with filing claims, while treatment recommendations are based on my dental needs rather than insurance limitations. I am responsible for charges above insurance benefits and for notifying the practice of insurance changes or services received from another provider during the benefit year.',
                        ],
                        ['key' => 'insurance_policy_initials', 'type' => 'digital_initials', 'label' => 'Initials: I understand the insurance information above', 'required' => true],
                        ['key' => 'financial_policy_heading', 'type' => 'heading', 'label' => 'Financial Policy'],
                        [
                            'key' => 'financial_policy_text',
                            'type' => 'paragraph',
                            'label' => 'The practice provides estimates of fees. The patient, parent, or guardian is responsible for the estimated patient portion on the date of service and for balances not paid by insurance, including procedures necessary for dental health that insurance does not cover. Claims are filed as a courtesy. I am responsible for contacting my insurer if a claim remains unpaid 45 days after service. A balance remaining after 45 days is my responsibility and may accrue interest at 3% to 5% per month. Accounts over 90 days may be referred to collections, with a collection fee of 4% plus applicable legal fees added to the balance.',
                        ],
                        [
                            'key' => 'financial_options_text',
                            'type' => 'paragraph',
                            'label' => 'Available payment options may include cash or check for established patients, major debit or credit cards, and an extended payment plan subject to credit approval. First-time patients pay by cash or credit card. Other financial arrangements must be approved before treatment.',
                        ],
                        [
                            'key' => 'treatment_responsibility_text',
                            'type' => 'paragraph',
                            'label' => 'I am responsible for completing treatment and following the recommended maintenance schedule. Delayed treatment, missed appointments, or failure to follow the maintenance plan may adversely affect teeth, supporting tissues, adjacent or opposing teeth, muscles, joints, and overall dental health. A prosthetic case will not be seated or delivered unless the balance is paid in full.',
                        ],
                        ['key' => 'financial_policy_initials', 'type' => 'digital_initials', 'label' => 'Initials: I understand the financial and treatment information above', 'required' => true],
                        ['key' => 'appointment_policy_heading', 'type' => 'heading', 'label' => 'Appointment Commitment'],
                        [
                            'key' => 'appointment_policy_text',
                            'type' => 'paragraph',
                            'label' => 'Elite Smiles reserves qualified team members and clinical time for each appointment. If I need to change an appointment, I will provide at least 48 hours notice. A missed appointment or late cancellation may result in a fee of $75 per provider, per reserved hour.',
                        ],
                        ['key' => 'appointment_policy_initials', 'type' => 'digital_initials', 'label' => 'Initials: I understand the appointment commitment above', 'required' => true],
                        ['key' => 'office_policy_acknowledgement', 'type' => 'acknowledgement_checkbox', 'label' => 'I understand and agree to the policies above and accept responsibility for any remaining balance on my account.', 'required' => true],
                        ['key' => 'office_policy_signature', 'type' => 'digital_signature', 'label' => 'Signature of patient, parent, or guardian', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'photo_image_consent',
                    'template_key' => 'elite_smiles_photo_image_consent',
                    'title' => 'Photo and Image Consent',
                    'description' => 'Choose whether Elite Smiles may use selected images.',
                    'category' => 'consent',
                    'fields' => [
                        ['key' => 'photo_heading', 'type' => 'heading', 'label' => 'Consent for Photo and Image Use'],
                        ['key' => 'photo_intro_text', 'type' => 'paragraph', 'label' => 'I, the undersigned, hereby authorize the office of Dr. Walter Meden to use the image categories selected below in a book of case samples, or for marketing or advertising purposes.'],
                        [
                            'key' => 'photo_permission',
                            'type' => 'radio',
                            'label' => 'Choose one',
                            'options' => ['I authorize the selected uses below', 'I do not authorize marketing or advertising use of my images'],
                            'required' => true,
                        ],
                        [
                            'key' => 'photo_image_types',
                            'type' => 'checkbox_group',
                            'label' => 'Images authorized for a case-sample book, marketing, or advertising',
                            'options' => [
                                'Before and after pictures of my teeth',
                                'Before and after pictures of my full face',
                                'Before and after pictures of the teeth and/or full face of my minor child',
                            ],
                        ],
                        [
                            'key' => 'photo_release_text',
                            'type' => 'paragraph',
                            'label' => 'By signing this authorization I waive any claims of breach of privacy pertaining to the release of any photographic or digital images as checked above. I acknowledge that I have received a copy of the privacy policies of this office. Declining marketing use will not affect my treatment.',
                        ],
                        ['key' => 'photo_patient_name', 'type' => 'text', 'label' => 'Patient name', 'required' => true],
                        ['key' => 'photo_signer_relationship', 'type' => 'text', 'label' => 'Signer relationship to patient', 'required' => true],
                        ['key' => 'photo_initials', 'type' => 'digital_initials', 'label' => 'Initials: I confirm the image-use choice above', 'required' => true],
                        ['key' => 'photo_acknowledgement', 'type' => 'acknowledgement_checkbox', 'label' => 'My signature confirms the photo and image choice above.', 'required' => true],
                        ['key' => 'photo_signature', 'type' => 'digital_signature', 'label' => 'Signature of patient or parent', 'required' => true],
                    ],
                ],
                [
                    'section_key' => 'final_review',
                    'template_key' => 'elite_smiles_final_review',
                    'title' => 'Review and Submit',
                    'description' => 'Review the information and submit the completed packet.',
                    'category' => 'review',
                    'fields' => [
                        ['key' => 'review_heading', 'type' => 'heading', 'label' => 'Review your forms'],
                        ['key' => 'review_message', 'type' => 'paragraph', 'label' => 'Please review your answers below. When everything is correct, submit the packet to Elite Smiles.'],
                    ],
                ],
            ],
        ];
    }
}
